### ISSUE TITLE
开发环境

### ISSUE THREAD

**Issue by Dream-Runner-Yu** [DreamWaterFound/KinectFusionAppLib_comments#1]
难道  泡泡机器人就没人用容器？？？？？？？？？？？？？？？？？？

**Comment by DreamWaterFound** [comment]
感谢反馈！:thumbsup:

- 这个仓库除了是因为泡泡的线下会议作为补充材料发布，其他和泡泡没有太大关系，所以还是不要把锅甩给泡泡机器人:sweat_smile:；

- 这个仓库没有提供容器的支持，一是因为原作者没有使用；二是它的环境配置相对比较简单（可以看CMakeLists.txt中就只CUDA，OpenCV，Eigen这三项依赖），导致我没有想到使用容器打包代码仓库

- 非常感谢你的提醒，我会尝试使用容器打包代码。使用容器确实是我们很多同学没有注意到的问题。
