### ISSUE TITLE
问支持CUDA的EIGEN怎么弄呀，Eigen库不是都是头文件吗，还能编译吗

### ISSUE THREAD

**Issue by Liuzhuoqiang** [DreamWaterFound/KinectFusionAppLib_comments#10]

**Comment by DreamWaterFound** [comment]
CMake之后，使用ccmake或者 CmakeGUI 修改相关变量，指向你要使用的CUDA的安装路径即可。随后重新配置并生成Makefile就可以了。虽然Eigen本身由头文件组成，但是cmake和make install的过程中，会修改和重新生成部分头文件。

**Comment by Liuzhuoqiang** [comment]
好的，谢谢大佬解答
