### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by shenglunch** [DreamWaterFound/KinectFusionAppLib_comments#2]
请问您是怎么配置的环境？
我在调用cv::cuda::getCudaEnabledDeviceCount()后得到0。
难道是GPU不行？目前只有MX150。。。

编译opencv的配置是，
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local/opencv-3.4.6 \
    -DOPENCV_EXTRA_MODULES_PATH=../modules/opencv_contrib-3.4.6/modules/ \
    -DBUILD_PNG=OFF \
    -DBUILD_TIFF=OFF \
    -DBUILD_TBB=OFF \
    -DBUILD_JPEG=OFF \
    -DBUILD_JASPER=OFF \
    -DBUILD_ZLIB=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_JAVA=OFF \
    -DBUILD_opencv_python2=OFF \
    -DBUILD_opencv_python3=ON \
    -DWITH_OPENCL=OFF \
    -DWITH_OPENMP=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_GSTREAMER=OFF \
    -DWITH_GSTREAMER_0_10=OFF \
    -DWITH_CUDA=ON \
    -DWITH_GTK=ON \
    -DWITH_VTK=OFF \
    -DWITH_TBB=ON \
    -DWITH_1394=OFF \
    -DWITH_OPENEXR=OFF \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \
    -DCUDA_ARCH_BIN='3.0 3.5 5.0 6.0 6.2' \
    -DCUDA_ARCH_PTX="" \
    -DINSTALL_C_EXAMPLES=OFF \
    -DINSTALL_TESTS=OFF ..

**Comment by csl1994** [comment]
难道是GPU不行？目前只有用的MX150

**Comment by DreamWaterFound** [comment]
不好意思才看到……不知道你有没有解决……

如果没有解决的话，我觉得可以先试试当初安装CUDA的时候附带的样例，编译的/1_Utilities/deviceQuery并运行，看看能否正确检测到GPU；
如果要是能的话，不妨单独自己写一个使用OpenCV CUDA模块的小程序，验证一下自己写的小程序是否也有同样的问题
