### ISSUE TITLE
Frame could not be processed

### ISSUE THREAD

**Issue by Apeiria** [DreamWaterFound/KinectFusionAppLib_comments#3]
您好，
我在尝试使用realsense运行的时候，从第二帧开始就一直输出 Frame could not be processed, icp 一直失败。不知道您有没有遇到过这个问题？第一帧的重建好像就没有成功，imshow("Pipeline Output", pipeline.get_last_model_frame());输出的图像是全黑的，导出mesh是空的。我尝试了使用tum数据集作为输入，现象也是相同的。

这是我使用realsense时控制台的输出，希望得到您的帮助，谢谢！
```
Found 1 CUDA devices
Device #0: GeForce RTX 2070 SUPER with 7979MB total memory
Using device #0
Using this RealSense device:
  Name                 : Intel RealSense D435
  Serial Number        : 746612070469
  Firmware Version     : 05.11.06.250
  Recommended Firmware Version : 05.12.06.00
  Physical Port        : /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb2/2-3/2-3:1.0/video4linux/video0
  Debug Op Code        : 15
  Advanced Mode        : YES
  Product Id           : 0B07
  Camera Locked        : YES
  Usb Type Descriptor  : 3.2
  Product Line         : D400
  Asic Serial Number   : 805513020863
  Firmware Update Id   : 805513020863
  Ip Address           : Not supported
Frame could not be processed
Frame could not be processed
Frame could not be processed
Frame could not be processed
Frame could not be processed
```

**Comment by DreamWaterFound** [comment]
我之前也是用 D435 跑得demo，印象中只有相机深度图像有效部分比较少的时候会出现这样的问题；不过从你反映的跑TUM RGB-D也错误来看，应该不是这个原因；现在我们实验室所有的RGB-D相机都被老师拿走给师弟了……暂时没有办法帮你复现错误；不过我想会不会我在加注释的时候误修改了某些代码，你要不试一试原作者仓库里面的程序能否正常运行呢？

**Comment by Apeiria** [comment]
我试了一下使用原作者仓库的程序运行，也是相同的现象

**Comment by jhljx** [comment]
卧槽，找到组织了。我也是用作者的源程序，结果第二帧开始就是ICP失败导致Frame could not be processed。我用的是https://github.com/ScanNet/ScanNet 这个数据中的scene0000_00。

看来不是我自己的问题。

**Comment by jhljx** [comment]
老铁，我已经发现问题是啥了。需要修改一下KinectFusionLib中的CMakeList.txt。把CUDA配置那块改成是和自己服务器GPU相同的配置。

我这里把

    SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3;-std=c++11 -gencode arch=compute_52,code=sm_52)

改成了

    SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3;-std=c++11 -gencode arch=compute_61,code=sm_61)

因为我的服务器GPU是GeForce GTX 1080 Ti，我在这个网站https://www.myzhar.com/blog/tutorials/tutorial-nvidia-gpu-cuda-compute-capability/ 找到了我这个GPU对应的compute capability。

改完这个之后再运行，mesh也不是空的了。而且当frame之间的motion很小的时候，每个frame都不会出现上述的Frame could not be processed的问题。

**Comment by DreamWaterFound** [comment]
> 老铁，我已经发现问题是啥了。需要修改一下KinectFusionLib中的CMakeList.txt。把CUDA配置那块改成是和自己服务器GPU相同的配置。
> 
> 我这里把
> 
> ```
> SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3;-std=c++11 -gencode arch=compute_52,code=sm_52)
> ```
> 
> 改成了
> 
> ```
> SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3;-std=c++11 -gencode arch=compute_61,code=sm_61)
> ```
> 
> 因为我的服务器GPU是GeForce GTX 1080 Ti，我在这个网站https://www.myzhar.com/blog/tutorials/tutorial-nvidia-gpu-cuda-compute-capability/ 找到了我这个GPU对应的compute capability。
> 
> 改完这个之后再运行，mesh也不是空的了。而且当frame之间的motion很小的时候，每个frame都不会出现上述的Frame could not be processed的问题。

非常感谢您的分享！

**Comment by abhijaysingh** [comment]
Hi @DreamWaterFound, I'm facing the same 'Frame could not be processed' issue. I followed @jhljx's suggestion but the error seems to persist. Is there any modification in the code that needs to be made for this to work?

``
Found 1 CUDA devices
Device #0: NVIDIA GeForce RTX 2080 with 7973MB total memory
Using device #0
Using this RealSense device:
  Name                 : Intel RealSense L515
  Serial Number        : f0140784
  Firmware Version     : 01.05.05.00
  Recommended Firmware Version : 01.05.05.00
  Physical Port        : /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video2
  Debug Op Code        : 15
  Advanced Mode        : Not supported
  Product Id           : 0B64
  Camera Locked        : YES
  Usb Type Descriptor  : 3.2
  Product Line         : L500
  Asic Serial Number   : 0003a895d324
  Firmware Update Id   : 0003a895d324
  Ip Address           : Not supported
Frame could not be processed
Frame could not be processed
Frame could not be processed

**Comment by zhuisa** [comment]
@Apeiria 请问如何运行TUM下载的数据呢？需要修改哪些地方呢
