### ISSUE TITLE
TSDF 计算疑问

### ISSUE THREAD

**Issue by nizihabi** [DreamWaterFound/KinectFusionAppLib_comments#5]
你好，最近在拜读KinectFusionLib的代码，根据你的注释和解说视频，明白了很多，但是有一个地方不是很理解，就是TSDF的计算，按照公式来算，是 ( a||tgk - p|| - Rk(X) ) ，这个结果，如果体素位于物体表面之前，那么 a||tgk - P|| 得到的深度应该是比实际观察点的深度 Rk(X) 小的，那么这个tsdf值应该是个负数，但是我看别的资料和博客，对于tsdf的描述都是：“位于表面之前为正”  ；这一步不是很理解，望解答。谢谢

**Comment by nizihabi** [comment]
已经搞明白了，谢谢代码注释分享

**Comment by DreamWaterFound** [comment]
不好意思才看到:joy: 解决了就好
