### ISSUE TITLE
设备使用问题？

### ISSUE THREAD

**Issue by xkyl-yhw** [DreamWaterFound/KinectFusionAppLib_comments#6]
您好。我想用kinectv2来跑这个程序可以吗？该如何配置呢？我环境已经配置好了。而且也把库中的代码build好了。没有错误。但不知道怎么设置才能使用自己的设备。麻烦帮我看看。
这是显示的错误

terminate called after throwing an instance of 'std::invalid_argument'
  what():  You have to specify a path to the configuration file
*** Failure: /home/xkyl/kinectfusion/jczeng1212-KinectFusionAppLib_comments-master/KinectFusionAppLib_comments/bin/KinectFusionApp has crashed ***

**Comment by DreamWaterFound** [comment]
可以是可以，但这个KinectFusion实现的原作者并没有增加对Kinect2的相机支持，你需要继承DepthCamera类，写一个专门操作Kinect2的类实现获取彩色图和深度图的操作。

**Comment by xkyl-yhw** [comment]
好的好的。还有一个问题。就是上面的报错我有点不太明白。是配置错误？我该怎么修改？

**Comment by xkyl-yhw** [comment]
![图片](https://user-images.githubusercontent.com/44514901/117277806-c2b48200-ae92-11eb-912d-9b5aba93ddc8.png)
terminate called after throwing an instance of 'std::invalid_argument'
what(): You have to specify a path to the configuration file
*** Failure: /home/xkyl/kinectfusion/jczeng1212-KinectFusionAppLib_comments-master/KinectFusionAppLib_comments/bin/KinectFusionApp has crashed ***
![图片](https://user-images.githubusercontent.com/44514901/117277969-ed063f80-ae92-11eb-8807-ee9ab068c507.png)

这个错误我不太知道是什么意思？我该怎么修改呢？
