### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by xkyl-yhw** [DreamWaterFound/KinectFusionAppLib_comments#7]
![图片](https://user-images.githubusercontent.com/44514901/117277806-c2b48200-ae92-11eb-912d-9b5aba93ddc8.png)
terminate called after throwing an instance of 'std::invalid_argument'
what(): You have to specify a path to the configuration file
*** Failure: /home/xkyl/kinectfusion/jczeng1212-KinectFusionAppLib_comments-master/KinectFusionAppLib_comments/bin/KinectFusionApp has crashed ***
![图片](https://user-images.githubusercontent.com/44514901/117277969-ed063f80-ae92-11eb-8807-ee9ab068c507.png)

这个错误我不太知道是什么意思？我该怎么修改呢？

**Comment by DreamWaterFound** [comment]
运行的时候没给定配置文件，正确的命令行应该类似这样：

```
 ./bin/KinectFusionApp --config ./KinectFusionApp/config.toml
```

`config.toml`中的各种选项需要按照你自己的实际情况修改

**Comment by xkyl-yhw** [comment]
> 运行的时候没给定配置文件，正确的命令行应该类似这样：
> 
> ```
>  ./bin/KinectFusionApp --config ./KinectFusionApp/config.toml
> ```
> 
> `config.toml`中的各种选项需要按照你自己的实际情况修改

谢谢成功打开了。
