### ISSUE TITLE
PPT 101 页。 Ax-b=0 ---> A^TAx=A^Tb 错误

### ISSUE THREAD

**Issue by renhaofan** [DreamWaterFound/KinectFusionAppLib_comments#8]
这里是不对的。最小二乘min||Ax-b|| 不是直接Ax-b=0。因为Ax-b有可能永远不等于0。 而是要在A的解空间找到最合适的x使得  min||Ax-b||。可以用矩阵求导的方式来得到 A^TAx=A^Tb。更直观的方式是
for any a_{i}  (a_{i})^{T}(Ax-b)=0
-->A^TAx=A^Tb
a_{i}是A的列向量

**Comment by renhaofan** [comment]
![v](https://user-images.githubusercontent.com/25266337/122208783-5471cf00-ced6-11eb-938b-4c54286be950.png)

**Comment by Liuzhuoqiang** [comment]
请问支持CUDA的EIGEN怎么弄呀，Eigen库不是都是头文件吗，还能编译u吗

**Comment by Liuzhuoqiang** [comment]
请问支持CUDA的EIGEN怎么弄呀，Eigen库不是都是头文件吗，还能编译吗

**Comment by DreamWaterFound** [comment]
不好意思时隔多年才看issue. 感谢订正，原文表述有误，后续我会更新。非常感谢！
